### ISSUE TITLE
Configure s3 bucket so that we can read our data directly from it in python

### ISSUE THREAD

**Issue by collinprather** [msarmi9/Sparkle#11]
This looks like it is relatively straightforward. We basically just need to be able to read out data into a jupyter notebook, like Diane shows [here](https://github.com/dianewoodbridge/2019-msds694-example/blob/master/Week5_TakeHome/ex02.ipynb). She has a video up on canvas explaining the process. Looks like we'll need to configure the permissions policy of our s3 bucket.

**Comment by msarmi9** [comment]
@collinprather @steph-jung @ajcheon Glad we took care of this earlier today! Closing this issue.
