### ISSUE TITLE
All members of group run `dc-project-AC-timed.ipynb` on EMR and record run time.

### ISSUE THREAD

**Issue by collinprather** [msarmi9/Sparkle#14]
Per Diane's instructions, each of us must run Andy's `dc-project-AC.ipynb` notebook on a unique EMR cluster configuration, then we will compare the run times. She recommends putting all our `spark` data processing code into a single cell so we can easily capture the full running time. I have made that edit to Andy's notebook and renamed it to `dc-project-AC-timed.ipynb` - this will be posted in the `sparkle` slack channel.

It seems fairly open ended in terms of how our EMR cluster configurations differ, so I propose we all run the notebook with the default `m5.xlarge` instances, but all use a different number of instances. For simplicity, let's all use the following number of instances:
```
    Collin: 5 `m5.xlarge` instances
    Kevin: 4 `m5.xlarge` instances
    Andy: 3 `m5.xlarge` instances
    Stephanie: 2 `m5.xlarge` instances
    Matt: 1 `m5.xlarge` instances
```

So, when launching, my configuration looked like this:

<img width="713" alt="Screen Shot 2019-12-08 at 7 44 10 AM" src="https://user-images.githubusercontent.com/32135129/70391990-dbfc8a80-198f-11ea-805a-6458c4c83127.png">

For the project, it would probably be good for us all to get a screenshot of the cluster config while running, which you can get in the AWS console if you go to `EMR` -> `Clusters` -> (toggle your cluster) -> `View details` -> `hardware`. Mine looks like this:

<img width="1646" alt="Screen Shot 2019-12-08 at 7 58 03 AM" src="https://user-images.githubusercontent.com/32135129/70392081-bae86980-1990-11ea-9ca4-3780c5b6a527.png">

Finally, after getting things all set up, upload `dc-project-AC-timed.ipynb`, then run the entire notebook, then go down and toggle the `Spark Job Progress` under the big cell which contains all the `pyspark` data processing code to get your configuration's runtime. For example, with 5 `m5.xlarge` instances, my code took 12.11 seconds to run.

<img width="1501" alt="Screen Shot 2019-12-08 at 8 00 50 AM" src="https://user-images.githubusercontent.com/32135129/70392123-3b0ecf00-1991-11ea-9d8d-7ce34faf0950.png">

And once we all do that, we should be good to go! We can put all of our different configurations and run times into a nice table in our presentation. 👍

**Comment by ajcheon** [comment]
<img width="1124" alt="Screen Shot 2019-12-08 at 6 10 46 PM" src="https://user-images.githubusercontent.com/6558338/70402120-16454680-19e7-11ea-8dbd-dc5405748fd5.png">

<img width="996" alt="Screen Shot 2019-12-08 at 6 16 24 PM" src="https://user-images.githubusercontent.com/6558338/70402076-f746b480-19e6-11ea-90e6-0231c34bc7ba.png">

**Comment by kbengtsonwong** [comment]
<img width="1279" alt="Screen Shot 2019-12-08 at 7 23 11 PM" src="https://user-images.githubusercontent.com/28700073/70405286-80fb7f80-19f1-11ea-9d71-888ed8dcfc0a.png">
<img width="783" alt="Screen Shot 2019-12-08 at 7 32 03 PM" src="https://user-images.githubusercontent.com/28700073/70405298-88bb2400-19f1-11ea-8f53-02d937fc19b5.png">

**Comment by kbengtsonwong** [comment]
Seems kind of strange that Andy's and my times are faster than Collin's.  If we have more time, I'm open to the idea of adding more elaborate processing tasks to the big cell so that we can prove more definitively the differences.

**Comment by ajcheon** [comment]
With @kbengtsonwong's new functions, mine takes about **85s**.

**Comment by collinprather** [comment]
With @kbengtsonwong's new functions, mine takes **45.5s**.

**Comment by kbengtsonwong** [comment]
Mine takes **57.95s** with new functions.

**Comment by steph-jung** [comment]
It took 131.15s for mine!

**Comment by msarmi9** [comment]
My runtime is `149.85 s`

As I'm the last person to do this 😅, we're finally done! Closing issue.
