### ISSUE TITLE
Run `dc-project-AC-timed.ipynb` on EMR with scaled out cluster

### ISSUE THREAD

**Issue by msarmi9** [msarmi9/Sparkle#16]
**Task:** Run the same notebook (`dc-project-AC-timed.ipynb`) on `EMR` with scaled out instances (more `ec2` instances, less computing power per instance). 

Curious to see how the same total amount of memory distributed to more worker nodes affects runtime performance (e.g. `8 workers at 8 GB RAM each` vs `4 workers at 16 GB RAM`)

Builds upon #14 

-----------

Each config group will be run with `1 or 3 m5.xlarge master nodes` and `x` number of `m4.large worker nodes (8 GB RAM)`

```
Config 1: 10 workers 
Config 2: 8 workers
Config 3: 6 workers
Config 4: 4 workers
Config 5: 2 workers
```

**Comment by msarmi9** [comment]
Config 1 Runtimes with 3 master nodes
* Trial 1: `63.63 s`
* Trial 2: `111.23 s`
* Trial 3: `59.91 s`
* Trial 4: `59.23`
* Trial 5: `59.81`

Config 1 Runtimes with 1 master node
* Trial 1: `58.60 s`
* Trial 2: `53.51 s`
* Trial 3: `112.90 s`
* Trial 4: `122.13 s`
* Trial 5: `110.97 s`

**Comment by msarmi9** [comment]
Config 2 Runtimes with 1 master node:
* Trial 1: `69.28 s`
* Trial 2: `112.5 s`
* Trial 3: `70.11 s`
* Trial 4: `62.61 s`
* Trial 5: `110.12 s`

**Comment by msarmi9** [comment]
Config 3 Runtimes with 1 master node:
* Trial 1: `81.53 s`
* Trial 2: `115.45 s`
* Trial 3: `115.21 s`
* Trial 4: `75.63 s`
* Trial 5: `72.17 s`

**Comment by msarmi9** [comment]
Config 4 Runtimes with 1 master node:
* Trial 1: `104.42 s`
* Trial 2: ` 102.22 s`
* Trial 3: `101.40 s`
* Trial 4: `97.19 s`
*  Trial 5: `101.92 s`

**Comment by steph-jung** [comment]
Config 5 Runtimes with 1 master note:

- Trial 1: `173.11 s`
- Trial 2: `169.89 s`
- Trial 3: `167.10 s`
- Trial 4: `170.05 s`
- Trial 5: `165.27 s`

**Comment by steph-jung** [comment]
Config 4(2nd trial) Runtimes with 1 master node:

Trial 1: `106.64 s`
Trial 2: `103.93 s`
Trial 3: `98.24 s`
Trial 4: `97.58 s`
Trial 5: `97.04 s`
