### ISSUE TITLE
Train Models on Various Cluster Configurations

### ISSUE THREAD

**Issue by msarmi9** [msarmi9/Sparkle#30]
**Task:** Train different models on various `emr` clusters. Record `cluster_configuration` and `model_runtime` in `/docs/cluster_performance.csv`, which has the following header: 

```
model;model_params;n_nodes;instance_type;n_records;n_features;train_time
```

**Note:** The field delimiter is `;` NOT `,`

Ex:
* `model = GBRegressor`
* `model_params = {maxIter: 150, nfolds: 10}` (leave empty `{}` if set to defaults)
* `n_nodes = 3` (1 `master` and 2 `workers`)
* `instance_type = m5.xlarge`
* `n_records = 240`
* `n_features = 102`
* `train_time = 35s`

**Comment by kbengtsonwong** [comment]
Done (instead using the GBT classifier model using 1 - 5 core nodes)
Slide populated in the deck
