### ISSUE TITLE
WatchOS -- Get audio data

### ISSUE THREAD

**Issue by collinprather** [msarmi9/Sparkle#60]
Right now, [CoreMotion](https://developer.apple.com/documentation/coremotion) provides us with all the movement-related sensor data that we need (accelerometer, gyroscope, etc). As far as I can tell, it will not give us any audio data. 

For the time being, we can proceed without it, but ideally we'll be able to find another way to get to it, and feed it into the existing pipeline, directly into s3.

**Comment by msarmi9** [comment]
Out of concerns for privacy we've decided to not include audio as a feature. Although @kbengtsonwong mentioned that we could potentially use just audio _intensity_ as a feature. Regardless, the model merged in PR #104 is achieving great results without audio. Closing.
