### ISSUE TITLE
Configure Sphinx auto-documentation to integrate with readthedocs

### ISSUE THREAD

**Issue by collinprather** [msarmi9/Sparkle#89]
Currently, our docs are successfully hosted at [https://sparkleai.readthedocs.io/en/latest/index.html](https://sparkleai.readthedocs.io/en/latest/index.html), however, the [code documentation](https://sparkleai.readthedocs.io/en/latest/code.html) page is blank.

I'm not sure what the issue is, but maybe it is something similar to [this](https://github.com/readthedocs/readthedocs.org/issues/4210), where there is a warning buried in our readthedocs build?

**Comment by ajcheon** [comment]
Are these docs currently pointed to `public master`?  If so we might have overwritten the comments in the huge `web` PR.  I can re-insert them back by c/p from `classroom master`.

**Comment by msarmi9** [comment]
@ajcheon Yep, the docs point to the `Sparkle/master` branch. Thnx @collinprather for the tip. I checked the build logs and sure enough, we've got a problem, Houston. 

<img width="761" alt="image" src="https://user-images.githubusercontent.com/48395294/79513851-b5afc100-7ff9-11ea-87a1-281fce2d733e.png">

Fortunately, should be a quick fix. We just need to add the dependencies for `app/` to `docs/requirements.txt`

**Comment by msarmi9** [comment]
Well, shoot. Fixed the `NoModuleFound` warnings, but we're getting a third warning now

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/48395294/79515865-99fae980-7ffe-11ea-85ab-96195cde3e38.png">

(Sorry, couldn't capture the entire error log). It says `html_static_path_entry` .. `docs/source/_static` does not exist. 

I think it might be looking for the `docs/build/_static`. We can update `html_static_path_entry` in our `docs/conf.py`

**Comment by collinprather** [comment]
ohhh, I actually have that folder locally, but since it is empty I don't think it's getting stored in git. I need to add a `.gitkeep` file in there!

**Comment by msarmi9** [comment]
Thanks to PR #103 we're able to host our docs on our own GitHub page and don't need to go through `readthedocs` anymore.
